version: 2.0

jobs:
  build:
      docker:
        - image: circleci/python:3.6.1
      steps:
        - checkout
        - run: echo ["build step", "taple message"]
        - run: python ./manage.py

workflow:
  version: 2
  build_and_test:
    jobs:
      - build
