version: 2.0

jobs:
  build:
      docker:
        - image: circleci/python:3.6.1
      steps:
        - checkout
        - run:
          name: echo
          command: echo build step
  test:
      docker:
        - image: circleci/python:3.6.1
      steps:
        - checkout
        - run:
          name: echo
          command: echo test step

workflow:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
