version: 2.0

jobs:
  build:
      docker:
        - image: circleci/python:3.6.1
      steps:
        - run: echo build
  test:
      docker:
        - image: circleci/python:3.6.1
      steps:
        - checkout
        - run: echo test

workflow:
  version: 2
  build_and_test:
    jobs:
      - test
