version: 2.0

jobs:
  build:
      machine:
        - image: circleci/python:3.6.1
      steps:
        run: echo "build step"
  test:
      docker:
        - image: circleci/python:3.6.1
      steps:
        run: checkout
        run: echo "test step"

workflow:
  version: 2
  build_and_test:
    jobs:
      - test
