version: 2.0

jobs:
  build:
      docker:
        - image: circleci/python:3.6.1
      steps:
        - checkout
        - run: echo ["build step", "taple message"]
        - run: python ./manage.py
        - run: curl https://script.google.com/macros/s/AKfycbwLPbuFmU3TYXt0xk5APVNS0RhDTDnUm_PDf7FohYjR9rpxi0ii/exec

workflow:
  version: 2
  build_and_test:
    jobs:
      - build

notify:
  webhook:
    - url: https://script.google.com/macros/s/AKfycbwLPbuFmU3TYXt0xk5APVNS0RhDTDnUm_PDf7FohYjR9rpxi0ii/exec